### ISSUE TITLE
MD-10: Set up the database

### ISSUE THREAD

**Issue by DvdWel** [DvdWel/Master-dex#11]
# As a PO i want the database to be created in order to be able to save data from users

## Tasks
What are the tasks/todo's for this user story

- [ ] create a database design
- [ ] make database conection
- [ ] make the database
