### ISSUE TITLE
MD-02: create login system

### ISSUE THREAD

**Issue by Danny-Mus** [DvdWel/Master-dex#3]
# MD-02: As a PO i want there to be an login system in order to create and save users which will be needed later for creating and saving teams

## Tasks
What are the tasks/todo's for this user story

- [ ] Create frontend login page (non-functional)
- [ ] Make the frontend login page functional

- [ ] Create backend database for data to be stored
- [ ] Allow user data to be saved from frontend 

## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
