### ISSUE TITLE
MD-03: Get Pokemon list

### ISSUE THREAD

**Issue by Danny-Mus** [DvdWel/Master-dex#4]
# MD-03: As a PO i want an list of all pokemons available.

## Tasks
What are the tasks/todo's for this user story

- [ ] Create page to display all the pokemons
- [ ] Get all the pokemons from `PokéAPI`
- [ ] style and display all the pokemons in blocks/cards
- [ ] add background color of each block/card depending on that pokemons type

## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
