### ISSUE TITLE
MD-05: Create general styling

### ISSUE THREAD

**Issue by Danny-Mus** [DvdWel/Master-dex#6]
# MD-05: As a PO i want general styling for the project

## Tasks
What are the tasks/todo's for this user story

- Mixins
- [ ] Create button mixin
- [ ] Create input mixin
- [ ] Create radiobutton mixin
- [ ] Create font mixin

- Variables
- [ ] Create variables (colors, fonts)

- Normalize
- [ ] Create normalize

## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
