### ISSUE TITLE
MD-09: indepth pokemon info

### ISSUE THREAD

**Issue by Danny-Mus** [DvdWel/Master-dex#9]
# MD-09: As a PO i want to see or read the pokemons info when i click on it.

## Tasks
What are the tasks/todo's for this user story

- [ ] Discuss if this is gona be an new page or somekind of popup. !important;

- When you click on a pokemon see indepth info of it (Moves, types, weak/strong against, Egg group, Evolution chain, description)
- [ ] Display '**Moves**'
- [ ] Display '**Types**'
- [ ] Display '**Generation**'
- [ ] Display '**Weak/strong against**'
- [ ] Display '**Egg group**'
- [ ] Display '**Evolution chain**'
- [ ] Display '**Description**'
- [ ] Display '**Gender**'
- [ ] Display '**Growth rate**'
- [ ] Display '**Weight**'
- [ ] Display '**Height**'
- [ ] Display '**Base experience**'
- [ ] Display '**stats**'

- Perhaps this could be categorized in tabs.

## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
